language: python
python:
- '3.8'
cache:
  pip: true
  directories:
    - #HOME/patent_client
install:
- pip install --upgrade pip
- pip install pandas
- pip install poetry
- poetry install
script:
- pytest --cov=./
- codecov
env:
  global:
  - secure: "aR3as+DuZQH/Wteu5a3kuT2FvImo7pHyZ4LTViNsiFrpOT4rCC7ou1vqWbC2zj33JMo1zWKXT+Q4QIl+mmRCqwRNNazjVOlCDn9XxVYPItkCxHJKRK64MXSYetdmH+XnkCcTIzR0/B1l9n/C/tBGOoho+jxkfhQdOJXpFYmK67hZbyxGjW5GgymC7RrnVhVn/udmEz1v0edJqSNKkpi94Wlyj35bPr1dsQRSSU1ai3FTggOcfnSFHzPZO6nN9qF9wE21+tRWk7BzGFIkTj4GVnVupQpTI53UmKKsmYzI2nY34Fkg+2yXJQy3RCUFfC/WuPT0uPEbl1vUuJabqN8U0X/nbfsiUyHIbE5sVZrXzyKAAAgYwDF6f/KJ9XpGaaNqYYKuSMzHba3ZdpcgYnslFhcyd793Zlc/1fuHYLvFy8CyjkOL/QGq5tr0npUQWwUPSF8vsGI4x0MuxMtYTKW7Oy1Qq7UFq6UgTVZtkzFRfJea3RTqvhWsaEmPJ6d+yQmhan2ZF9sMTEIkeUEjE2Zxaeljhm1ZGdDbpMvpt5rV+yASJ2HEOTzgqn3Wmn/7mEyA/s7J0KYH2YsdG4fU+0cG+RAuDeiTFRQ5Tm95dntPG6T9g/WEUcdMJZrqN8m8xru92IbZILRKmOy+Q8dR/wN8j88eP7dgVot+vkuAYNaMoqk="
  - secure: "kzP0uMYeHO2pqqZCRKDi+pFhI6sQn4kIxp7YB4P7cltXZOSYVNygfbIJrsE0vMwUvCIrlAeTn6JFcYjpO5gmvwcoWM93lQ/BAbdxcPPZ9ibH8ms96v14lWLPYNJDUV4n4sCl4/HokxTtdNdM7WG5fH2eM26YSjw6J7TGbbgWlI9Fa6D0KCiKC7czf9IBF7uOJuWXihgY46xbzlToxxY2ngQweMTkNzFv267+nox8DhI6eo7LQqLwUbS73qyxkc5IxzFElEtzpPMPY8M/P7r8aVpeBKGupGxlOtDcppiia6VGsc2MTmb2DSE2MWBT47OY34iVGePjlM2i3BHufSoqtB8qvp57jzrHgiNrCgsJKX0ZVC8fxDP7Fe4btHSiCV5+4gFUh+wZjIw76dOvWGMm81nRPdTyRsf4HrmO6jYVQMrpp4vZEMAxcWk+2m25laKsh7nQxx2JMVfg3A5bLFvAMTYprsCoHIqiujCLhN5L4Yd+ovZurLP79n4aezJKsubOStosCG2Mn0peTfVLz4xfVqR97tJlQONsahv0UEGQCTUP84SC0CCRS1jq5jx4yyhEj1mFKz/YFWYXMXfaeMmP08mtv26ete3PphtQfLoF1+K/C1jZJNDuO+52z1mO2/J7CrVPZo4PEkFdkcgO971kymEagQkbWDtOo3iUhgywSUo="

deploy:
  provider: pypi
  username: pypatent2018
  distributions: sdist bdist_wheel
  password:
    secure: Rq7O/bXNCsAQVkynntRc49lqeoQ8maLInTuoPCniwCiwluzFeT/tKVsmht/Px41ns0ECVZCmXmt1qpZuBaDTEtLd3p+eMn1ZKjkzEVETNc42GdVrj22fAIJLhGY7DxMpn/2uqCo59XWncp9YKDWskhzTX/aiznQhqL9mq3OxWFpK6cCfRK8CL+4jdybENxLk+ziHwdv3ArR8JyZ5ADvu/WQy71PwWSrLZMrQVqY1Rxus66k0n9JkmxNovVuLYCs894LFvGriJ53dHxbuiZbkDEWxP21KbLl+vj/EslSkgcxOSVgL2we1wo9zuwrELN/SFEUgqB1MD8JkgKz85aOUg+6uOW5SgVA79yx+7GtpNoKvs6wDMHrBndF3QXAB6zZNXSkZi07PH+/SGNku3ltesbXiybZB33gBJ3ZUmTRZv43LCMwS316iOkKkyrKLhCuzmM/pIriB1jVQF8C2d3YQXKRgzyJ1VvOhOmizBGK+1S6EhlX3VUI5y3vUGHHOTrez8DPPRLRqC1VMIwtX9WdodYuTArYoZZ4V/VwAwD0cd6sH5vjlGKtK6xlNkI3+mZr5UPxDzRkv2sKU3k1C9+jwEf0H8OatjGIP1EOVLeUa+jg9CWBZtVdY8DMX6CpUm6LuZ3NroIBq7+F1YPI6ZULeFxU9udxm/x2RgSpksfTmbbI=
