interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - Mozilla/5.0 Python Patent Clientbot/3.2.5 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://developer.uspto.gov/ptab-api/proceedings?applicationNumberText=09089931&recordTotalQuantity=25&sortOrderCategory=
  response:
    body:
      string: "{\"aggregationData\":{},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
        Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
        Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
        HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
        a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
        McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - accept, authorization, content-type, x-requested-with
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS, PUT
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Max-Age:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Wed, 10 May 2023 15:45:04 GMT
      Strict-Transport-Security:
      - max-age=31536000;
      Transfer-Encoding:
      - chunked
      Vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - Mozilla/5.0 Python Patent Clientbot/3.2.5 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://developer.uspto.gov/ptab-api/proceedings?applicationNumberText=09089931&recordTotalQuantity=25&sortOrderCategory=&recordStartNumber=0
  response:
    body:
      string: "{\"aggregationData\":{},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
        Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
        Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
        HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
        a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
        McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - accept, authorization, content-type, x-requested-with
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS, PUT
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Max-Age:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Wed, 10 May 2023 15:45:04 GMT
      Strict-Transport-Security:
      - max-age=31536000;
      Transfer-Encoding:
      - chunked
      Vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    status:
      code: 200
      message: OK
version: 1
